### ISSUE TITLE
Throwing stones crashes the game:

### ISSUE THREAD

**Issue by MattConrad** [jeremygurr/dcssca#679] opened 2016-05-28 16:51 UTC
I've seen this on a couple different characters. Pick up stones, quiver them, throw at monster, game ends.

(Looks like the auto ammo has been removed, also.)

**Comment by jeremygurr** [comment] 2016-05-28 19:55
I can't seem to reproduce this. Is it happening with your character now? What is your character's name?

**Comment by MattConrad** [comment] 2016-05-28 21:50
Yes, my current saved game repros the bug for me. I am mattchew and you are welcome to take over the game (do not care about continuing).

Currently saved with stones quivered and a python on the screen. I get the crash either with ff or f.<enter>

Version: Dungeon Crawl Stone Soup: Circus Animals 1.5.4-6-ge650ac5
Platform: unix
Bits: 64
Game mode: normal
Tiles: online

Command line: /var/crawl/v1.5.4/bin/crawl -name mattchew -rc /var/crawl/rcs/mattchew.rc -macro /var/crawl/rcs/mattchew.macro -morgue /var/crawl/rcs/mattchew/ -wizard -webtiles-socket /var/crawl/rcs/mattchew:2016-05-28.21:47:47.sock -await-connection

RC options:
restart_after_game = false

Crash caused by signal #11: Segmentation fault

Obtained 16 stack frames.
/var/crawl/v1.5.4/bin/crawl(_Z17write_stack_traceP8_IO_FILEi+0x2d) [0xb0f805]: write_stack_trace(_IO_FILE*, int)
/var/crawl/v1.5.4/bin/crawl(_Z13do_crash_dumpv+0x3b7) [0xb19ac7]: do_crash_dump()
/var/crawl/v1.5.4/bin/crawl(_Z20crash_signal_handleri+0x273) [0xb0f669]: crash_signal_handler(int)
/lib64/libc.so.6(+0x385b0) [0x7f0df44255b0]: 
/var/crawl/v1.5.4/bin/crawl(_Z15fires_ammo_typeRK8item_def+0xc) [0xd588e8]: fires_ammo_type(item_def const&)
/var/crawl/v1.5.4/bin/crawl(_ZNK8item_def11launched_byERKS_+0x2e) [0xd74838]: item_def::launched_by(item_def const&) const
/var/crawl/v1.5.4/bin/crawl(_Z14weapon_sp_costPK8item_defS1_+0x89) [0x102d5bc]: weapon_sp_cost(item_def const_, item_def const_)
/var/crawl/v1.5.4/bin/crawl(_Z8throw_itR4boltR8item_defP4dist+0x859) [0x119e2a0]: throw_it(bolt&, item_def&, dist*)
/var/crawl/v1.5.4/bin/crawl(_Z10fire_thingi+0x23e) [0x119ceee]: fire_thing(int)
/var/crawl/v1.5.4/bin/crawl(_Z15process_command12command_type+0x13be) [0x12dad28]: process_command(command_type)
/var/crawl/v1.5.4/bin/crawl() [0x12d7d51]
/var/crawl/v1.5.4/bin/crawl() [0x12d483b]
/var/crawl/v1.5.4/bin/crawl() [0x12d4337]
/var/crawl/v1.5.4/bin/crawl(main+0x172) [0x12d4184]: 
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f0df4411bf5]: 
/var/crawl/v1.5.4/bin/crawl() [0xa203d9]

Trying to run gdb.
GNU gdb (Gentoo 7.10.1 vanilla) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
https://bugs.gentoo.org/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word".
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007f0df47a868a in waitpid () from /lib64/libpthread.so.0
#0  0x00007f0df47a868a in waitpid () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000b0fc60 in call_gdb (file=0x7f0df4793080 <_IO_2_1_stderr_>) at crash.cc:420
        gdb = 26777
        attach_cmd = "attach 26775\000\000\000\000\000\000\000"
#2  0x0000000000b19ae4 in do_crash_dump () at dbg-asrt.cc:718
        t = 1464472080
        dir = "/var/crawl/rcs/mattchew/"
        name = "/var/crawl/rcs/mattchew/crash-mattchew-20160528-214800.txt", '\000' <repeats 121 times>
        file = 0x7f0df4793080 <_IO_2_1_stderr_>
#3  0x0000000000b0f669 in crash_signal_handler (sig_num=11) at crash.cc:193
No locals.
#4  <signal handler called>
No symbol table info available.
#5  0x0000000000d588e8 in fires_ammo_type (item=...) at itemprop.cc:2128
No locals.
#6  0x0000000000d74838 in item_def::launched_by (this=0x7fff1d28c390, launcher=...) at items.cc:3320
        mt = MI_DART
#7  0x000000000102d5bc in weapon_sp_cost (weapon=0x0, ammo=0x7fff1d28c390) at player.cc:9752
        weight = 3
        fighting = 30584328
        benefit = 0
        sp_cost = 6.9531677784721977e-310
        strength = -1
#8  0x000000000119e2a0 in throw_it (pbolt=..., thrown=..., target=0x7fff1d28c540) at throw.cc:966
        weapon_used = 0x0
        ammo_used = 0x7fff1d28c390
        sp_cost = 32767
        returning = false
        ammo_brand = 0
        thr = {isValid = true, isTarget = true, isEndpoint = false, isCancel = false, choseRay = true, target = {x = 12, y = 11}, delta = {x = 0, y = 0}, ray = {r = {start = {x = 16.166666666666668, y = 16.5}, dir = {x = -2, y = -3}}, on_corner = false, cycle_idx = 0}}
        item = {base_type = OBJ_MISSILES, sub_type = 5 '\005', {plus = 0, mon_type = MONS_PROGRAM_BUG, skill = SK_FIGHTING, charges = 0, initial_cards = 0, net_durability = 0}, {plus2 = 0, used_count = 0, net_placed = 0, skill_points = 0, charge_cap = 0, stash_freshness = 0}, {special = 0, unrand_idx = 0, deck_rarity = DECK_RARITY_RANDOM, rod_plus = 0, subtype_rnd = 0, brand = 0, freshness = 0}, rnd = 18 '\022', quantity = 1, flags = 536903680, curse_weight = 0, id_complexity = 0, pos = {x = -1, y = -1}, link = 1, slot = 98, orig_place = {branch = BRANCH_DUNGEON, depth = 1}, orig_monnum = 0, inscription = "", props = {hash_map = 0x0}}
        wepType = 5
        cancelled = false
        unwielded = false
        did_return = false
        teleport = false
        projected = LRET_THROWN
        ammo_name = "a stone"
        wepClass = OBJ_MISSILES
        bow_brand = 0
        hit = false
#9  0x000000000119ceee in fire_thing (item=1) at throw.cc:535
        beam = {origin_spell = SPELL_NO_SPELL, range = 7, glyph = 40, colour = 6 '\006', flavour = BEAM_MISSILE, real_flavour = BEAM_MAGIC, drop_item = false, item = 0x7fff1d28c390, source = {x = 16, y = 16}, target = {x = 12, y = 11}, damage = {num = 0, size = 0}, ench_power = 0, hit = 0, thrower = KILL_YOU_MISSILE, ex_size = 0, source_id = 4294967295, source_name = "", name = "stone", short_name = "", hit_verb = "", loudness = 0, hit_noise_msg = "", explode_noise_msg = "", pierce = false, is_explosion = false, aimed_at_spot = false, aux_source = "", affects_nothing = false, effect_known = true, effect_wanton = false, draw_delay = 15, explode_delay = 50, special_explosion = 0x0, was_missile = true, evoked = false, animate = true, ac_rule = AC_NORMAL, obvious_effect = false, seen = false, heard = false, path_taken = std::vector of length 7, capacity 8 = {{x = 15, y = 15}, {x = 14, y = 14}, {x = 14, y = 13}, {x = 13, y = 12}, {x = 12, y = 11}, {x = 12, y = 10}, {x = 11, y = 9}}, extra_range_used = 0, is_tracer = false, is_targeting = false, aimed_at_feet = false, msg_generated = false, noise_generated = false, passed_target = true, in_explosion_phase = false, attitude = ATT_FRIENDLY, foe_ratio = 100, hit_count = std::map with 1 elements = {[3] = 1}, foe_info = {count = 1, power = 1, hurt = 0, helped = 0, dont_stop = false}, friend_info = {count = 0, power = 0, hurt = 0, helped = 0, dont_stop = false}, chose_ray = true, beam_cancelled = false, dont_stop_player = false, dont_stop_trees = false, bounces = 0, bounce_pos = {x = 0, y = 0}, reflections = 0, reflector = 0, use_target_as_pos = false, auto_hit = false, ray = {r = {start = {x = 16.166666666666668, y = 16.5}, dir = {x = -2, y = -3}}, on_corner = false, cycle_idx = 0}, tile_beam = -1, can_see_invis = false, nightvision = false, message_cache = std::set with 0 elements}
        target = {isValid = true, isTarget = true, isEndpoint = false, isCancel = false, choseRay = true, target = {x = 12, y = 11}, delta = {x = 0, y = 0}, ray = {r = {start = {x = 16.166666666666668, y = 16.5}, dir = {x = -2, y = -3}}, on_corner = false, cycle_idx = 0}}
        ammo = 0x1d2bd68 <you+4264>
        created_ammo = false
#10 0x00000000012dad28 in process_command (cmd=CMD_FIRE) at main.cc:2339
        player_moved = false
#11 0x00000000012d7d51 in _input () at main.cc:1527
        cmd = CMD_FIRE
        player_disabled = {was_disabled = false}
#12 0x00000000012d483b in _launch_game () at main.cc:504
        game_start = false
        ccon = {cstate = false, smartcstate = false}
#13 0x00000000012d4337 in _launch_game_loop () at main.cc:381
        game_ended = false
#14 0x00000000012d4184 in main (argc=13, argv=0x7fff1d28cd78) at main.cc:337
No locals.

Compilation info:
<<<<<<<<<<<
Compiled with GCC 4.7.3 on May 28 2016 at 19:55:18
Build platform: x86_64-pc-linux-gnu
Platform: x86_64-pc-linux-gnu
CFLAGS: -O0 -ggdb -pipe -DUSE_TILE -DUSE_TILE_WEB -DEXPERIMENTAL_BRANCH="v1.5.4" -Wall -Wformat-security -Wundef -Wno-array-bounds -Wno-format-zero-length -Wmissing-declarations -Wredundant-decls -Wno-parentheses -Wwrite-strings -Wshadow -pedantic -Iutil -I. -Irltiles -isystem contrib/install/x86_64-pc-linux-gnu/include -DDEBUG -DWIZARD -DCLUA_BINDINGS -DDGAMELAUNCH -DSHARED_DIR_PATH="/var/crawl/rcs" -isystem /usr/include/ncursesw
LDFLAGS: -rdynamic -O0 


Place info:
branch = 7, depth = 1

Level id: D:1
Level build method = random_map_for_place, level layout type  = rooms, absdepth0 = 0
Level vaults:
    evilmike_arrival_hilbert_curve
    layout_basic
    hangedman_decor_growths

Markers:
<<<<<<<<<<<<<<<<<<<<<<
Marker 0 at (40, 19): feature (stone_stairs_up_i)


Messages:
<<<<<<<<<<<<<<<<<<<<<<

Welcome, mattchew the Demonspawn Ice Elementalist.
You are playing the Challenge difficulty mode, Classic experience mode 
The bosom of this dungeon contains the fabled artefact, the Orb of Zot.
Press ? for a list of commands and other information. Found 7 gold pieces.
Found a staircase leading out of the dungeon.
A goblin comes into view. (hp=4, hd=1)
You miscast Freeze. You are very lightly contaminated with residual magic.
A chill runs through your body.
You miscast Freeze. Nothing appears to happen.
You miscast Freeze. Wisps of condensation drift from your hands.
You miscast Freeze. You feel uncomfortably cold.
You miscast Freeze. You feel a strange surge of energy!
You miscast Freeze. A chill runs through your body.
You miscast Freeze. Your hands feel numb with cold.
You freeze the goblin (1).
Unknown command.
You miscast Freeze. You shiver with cold. The goblin hits you (3).
You kill the goblin!
You freeze the goblin (7).
A bat comes into view. (hp=3, hd=1)
Unknown command.
You miscast Freeze. Your hands feel numb with cold. The bat barely misses you.
You kill the bat!
You freeze the bat (3).
A hobgoblin comes into view. (hp=5, hd=1) It is wielding a club.
The hobgoblin shouts!
You miscast Freeze. You are contaminated with residual magic.
You feel uncomfortably cold.
You miscast Freeze. You feel uncomfortably cold.
You miscast Freeze. Frost covers your body.
The hobgoblin hits you (6) with a club.
You were prevented from receiving too much damage! (6 -> 5)
You miscast Freeze. You feel uncomfortably cold.
You miscast Freeze. Frost covers your body.
Clearing travel trail.
Okay, then.
Unknown command.
You miscast Freeze. Frost spreads across the the floor.
You miscast Freeze. You feel uncomfortably cold.
Your body shudders with the violent release of wild energies!
You feel stupid.
You miscast Freeze.
You hear a crackling sound.
You miscast Freeze.
You hear a crackling sound.
Unknown command.
You kill the hobgoblin!
You freeze the hobgoblin (9).
A giant cockroach comes into view. (hp=5, hd=1)
The giant cockroach closely misses you.
You freeze the giant cockroach (3).
You miscast Freeze.
You hear a crackling sound.
You miscast Freeze. A chill runs through your body.
The giant cockroach bites you (1).
You miscast Freeze. A chill runs through your body.
You miscast Freeze. You feel a strange surge of energy!
You miscast Freeze. Your hands feel numb with cold.
You miscast Freeze. You feel a strange surge of energy!
You miscast Freeze. A chill runs through your body.
You miscast Freeze. Frost covers your body.
You miscast Freeze. A chill runs through your body.
Unknown command.
You miscast Freeze. You feel uncomfortably cold.
The giant cockroach bites you (1).
You miscast Freeze.
You hear a crackling sound.
You miscast Freeze. Wisps of condensation drift from your hands.
You miscast Freeze.
You hear a crackling sound.
You miscast Freeze. You feel uncomfortably cold.
You miscast Freeze. A chill runs through your body.
You miscast Freeze.
You feel more contaminated with magical energies.
A chill runs through your body.
You miscast Freeze. Nothing appears to happen.
You miscast Freeze. You feel a strange surge of energy!
You miscast Freeze. You feel uncomfortably cold.
The giant cockroach barely misses you.
You miscast Freeze. Frost covers your body.
You miscast Freeze. A chill runs through your body.
You miscast Freeze. You feel uncomfortably cold.
You miscast Freeze. A chill runs through your body.
You kill the giant cockroach!
You freeze the giant cockroach (7).
Unknown command.
Unknown command.
You don't know that spell.
Unknown command.
Okay, then.
Unknown command.
Unknown command.
You start waiting.
Your body shudders with the violent release of wild energies!
The magical storm engulfs you! (16)
You were prevented from receiving too much damage! (16 -> 5)
Damage (5) was greater than 30% of your hp (8)!!!
Your blood runs red-hot!
You start resting.
You hear a shout! x2
A kobold comes into view. (hp=3, hd=1) It is wielding a short sword.
The kobold throws a stone. The stone hits you (2).
The kobold throws a stone. The stone barely misses you.
The kobold throws a stone. The stone barely misses you.
The kobold throws a stone. The stone hits you (1).
You miscast Freeze. Nothing appears to happen.
You miscast Freeze. You feel a strange surge of energy!
You miscast Freeze. Frost covers your body.
You miscast Freeze. Wisps of condensation drift from your hands.
You miscast Freeze. Frost covers your body.
You kill the kobold!
You freeze the kobold (6).
Okay, then.
Unknown command.
You start waiting.
Your body shudders with the violent release of wild energies!
The magical storm engulfs you! (11)
You were prevented from receiving too much damage! (11 -> 5)
Damage (5) was greater than 30% of your hp (8)!!!
The acid burns!
You were prevented from receiving too much damage! (13 -> 0)
Your metabolism speeds up!
Unknown command.
You start resting.
You hear a shout! x3
You feel less contaminated with magical energies.
You start resting.
A giant cockroach comes into view. (hp=4, hd=1)
A giant cockroach is nearby!
A giant cockroach is nearby!
You freeze the giant cockroach (2).
You miscast Freeze.
You feel more contaminated with magical energies.
You feel a strange surge of energy! The giant cockroach barely misses you.
You kill the giant cockroach!
You freeze the giant cockroach (3).
You start waiting.
You feel less contaminated with magical energies.
You start waiting.
Your body shudders with the violent release of wild energies!
The magical storm engulfs you! (8)
You feel drained.
You were prevented from receiving too much damage! (8 -> 5)
Damage (5) was greater than 30% of your hp (8)!!!
You feel weirdly uncertain.
Unknown command.
Unknown command.
You start resting.
Your body shudders with the violent release of wild energies!
You feel clever.
You start resting.
Your body shudders with the violent release of wild energies!
You feel stupid.
You feel less contaminated with magical energies.
You start resting.
HP restored.
You start waiting.
A kobold comes into view. (hp=3, hd=1) It is wielding a short sword.
The kobold shouts!
You miscast Freeze. Frost spreads across the the floor.
You miscast Freeze. Nothing appears to happen.
You kill the kobold!
You freeze the kobold (4).
Okay, then.
Unknown command.
b - a fuming pink potion
You now have 5 gold pieces.
Items here: ))) Ã·Ã·Ã· â€ 
You start waiting.
Your magical contamination has completely faded away.
Found a runed naga barding.
Found a cloak.
Found a ring mail. You now have 12 gold pieces (gained 7).
Found 9 gold pieces.
b - 2 fuming pink potions (gained 1)
A hobgoblin comes into view. (hp=6, hd=1)
A rat comes into view. (hp=2, hd=1)
The hobgoblin shouts!
You see here 9 gold pieces.
You now have 21 gold pieces (gained 9).
There is an open door here.
You close the door.
A hobgoblin opens the door.
You freeze the hobgoblin (4).
You miscast Freeze. You are very lightly contaminated with residual magic.
Frost spreads across the the floor.
You kill the hobgoblin!
Your base Dodging skill increases to level 3!
You freeze the hobgoblin (3).
Okay, then.
Unknown command.
You start resting.
Okay, then.
Unknown command.
Unknown command.
You kill the rat!
You freeze the rat (2).
You start waiting.
Your magical contamination has completely faded away.
Things that are here:
a ring mail; a hobgoblin corpse
Found a stone staircase leading down.
As you open the door, it creaks loudly!
Found an escape hatch in the floor.
There is a stone staircase leading down here.
Found 32 stones.
c - a scroll labeled GOTHRU CAFENUATZ
You see here 32 stones.
b - 32 stones
Quivering b - 32 stones for throwing.
You are suddenly yanked towards a nearby monster!
Your surroundings suddenly seem different.
A ball python comes into view. (hp=3, hd=1)
Okay, then.
Saving game... please wait.
Welcome back, mattchew the Demonspawn Ice Elementalist.
You are playing the Challenge difficulty mode, Classic experience mode 
Welcome back, mattchew the Demonspawn Ice Elementalist.
You are playing the Challenge difficulty mode, Classic experience mode 
Press ? for a list of commands and other information.
You throw a stone.


Game state:

mouse_enabled: 0, waiting_for_command: 0, terminal_resized: 0
io_inited: 1, need_save: 1, saving_game: 0, updating_scores: 0:
seen_hups: 0, map_stat_gen: 0, type: 1, arena_suspended: 0

prev_cmd = CMD_FIRE
repeat_cmd = CMD_NO_CMD

Player:
{{{{{{{{{{{
Name:    [mattchew]
Species: Demonspawn
Job:     Ice Elementalist

HP: 13/13; mods: 0/0
MP: 90/90; mod: 0
Stats: 8 (8) 14 (14) 13 (13)
Position: (16, 16), god: No God (0), turn_is_over: 0, banished: 0
Standing on/in/over feature: floor

Skills (mode: manual)
Name            | can_train | train | training | level | points | progress
Fighting        |     X     |   0   |     0    |    0  |      0 | 0/50
Short Blades    |           |   0   |     0    |    0  |      0 | 0/59
Long Blades     |           |   0   |     0    |    0  |      0 | 0/59
Axes            |           |   0   |     0    |    0  |      0 | 0/59
Maces & Flails  |           |   0   |     0    |    0  |      0 | 0/59
Polearms        |           |   0   |     0    |    0  |      0 | 0/59
Staves          |           |   0   |     0    |    0  |      0 | 0/59
Slings          |           |   0   |     0    |    0  |      0 | 0/59
Bows            |           |   0   |     0    |    0  |      0 | 0/59
Crossbows       |           |   0   |     0    |    0  |      0 | 0/59
Throwing        |     X     |   0   |     0    |    0  |      0 | 0/59
Armour          |     X     |   0   |     0    |    0  |      0 | 0/59
Dodging         |     X     |   1   |    25    |    3  |    451 | 11/332
Stealth         |     X     |   1   |    25    |    1  |     61 | 11/120
Shields         |           |   0   |     0    |    0  |      0 | 0/59
Unarmed Combat  |     X     |   0   |     0    |    0  |      0 | 0/59
Spellcasting    |     X     |   1   |    25    |    2  |    332 | 130/238
Conjurations    |           |   0   |     0    |    1  |     51 | 1/120
Hexes           |           |   0   |     0    |    0  |      0 | 0/50
Charms          |           |   0   |     0    |    0  |      0 | 0/59
Summonings      |           |   0   |     0    |    0  |      0 | 0/50
Necromancy      |           |   0   |     0    |    0  |      0 | 0/42
Translocations  |           |   0   |     0    |    0  |      0 | 0/59
Transmutations  |           |   0   |     0    |    0  |      0 | 0/59
Fire Magic      |           |   0   |     0    |    0  |      0 | 0/59
Ice Magic       |     X     |   1   |    25    |    2  |    401 | 199/238
Air Magic       |           |   0   |     0    |    0  |      0 | 0/59
Earth Magic     |           |   0   |     0    |    0  |      0 | 0/59
Poison Magic    |           |   0   |     0    |    0  |      0 | 0/50
Invocations     |           |   0   |     0    |    0  |      0 | 0/29
Evocations      |           |   0   |     0    |    0  |      0 | 0/50

Spell bugs:

Durations:

Attributes:
    #12: 21
    #27: 14
    #35: 36
    #49: 61
    #59: 1
    #64: 60

Mutations:
    dopey: 1
    fast metabolism: 1
    ignite blood: 1
    teleportitis: 1

Inventory bugs:

Equipment:
    eq slot #6, inv slot #0: +0 robe

}}}}}}}}}}}

Webtiles message buffer: 
Webtiles JSON stack:

Screenshot:
######+#####....#     ..#
................#####...#
.........................
....S..$.................
.........................
.........................
........#....###.###.....
........#....###.# #.....
........@........###.....
..........>............++
######.................##
  ...........#.#.......##
  .......................
 ..................#.....
 .........#.#......##'#..
 #.......##.#.....###.#..
  ......>+........# #.#..

clua stack:

dlua stack:

Lua persistent data:
<<<<<<<<<<<<<<<<<<<<<<


Lua marker contents:
<<<<<<<<<<<<<<<<<<<<<<

**Comment by jeremygurr** [comment] 2016-05-29 00:50
Ok I grabbed it. You can continue if you wish since I have a copy of your save locally.

**Comment by jeremygurr** [comment] 2016-05-29 00:59
Ok fixed now. That save file made it easy to track down.

**Comment by MattConrad** [comment] 2016-05-29 01:01
Wow, you're quick. Thanks.

**Closed as completed** 2016-05-29 01:13 UTC
